import '@/styles/globals.css'
import type { Metadata } from 'next'
import { Mulish } from 'next/font/google'
import { Providers } from './provider'
import { Header } from '@/components/Header'
import { Footer } from '@/components/Footer'

const mulish = Mulish({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Camada',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html suppressHydrationWarning lang="en">
      <head />
      <body className={mulish.className}>
        <Providers>
          <Header />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
